### ISSUE TITLE
File cannot be created on Windows due to ":" in filename

### ISSUE THREAD

**Issue by karl-barbour** [newrelic-experimental/nr-find-log4j#5]
## Description

When running the tool, the file cannot be created as `new Date()).toISOString()` results in a filename containing illegal characters (`:`).

## Steps to Reproduce

Execute file `node nr-find-log4j.js`

## Expected Behavior

Script runs and produces CSV/JSON output file.

## Relevant Logs / Console output

```
Checking api key...  OK, found 215 accounts.
Scanning your accounts, this may take some time...
Checking 109 java services... done. Actual service count is 109.
Scanning modules (service 109 of 109)...  done.

OK, scan took 81 seconds. Found 15 services with log4j-core.
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'log4j_scan_2021-12-14T13:30:13.870Z.csv'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2153:35)
    at writeResults (D:\git\nr-find-log4j\nr-find-log4j.js:542:8)
    at findModulesByEntity (D:\git\nr-find-log4j\nr-find-log4j.js:367:3)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async findServices (D:\git\nr-find-log4j\nr-find-log4j.js:281:5)
    at async D:\git\nr-find-log4j\nr-find-log4j.js:199:7 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'log4j_scan_2021-12-14T13:30:13.870Z.csv'
}
```

## Your Environment

Windows 11 
Tested on Node 14, Node 16

## Additional context

n/a

**Comment by karl-barbour** [comment]
Created pull request #6 to resolve
